appName: catalogue
params: "prod.catalogue.mongo_url prod.catalogue.documentdb"
appPort: 8080
schema:
  enabled: true
  type: mongo

resources:
   limits:
     cpu: 500m
     memory: 712Mi
   requests:
     cpu: 300m
     memory: 512Mi
